spring:
  datasource:
    driverClassName: org.h2.Driver
    password: h,Y9RTV?=VJ!7zu=
    url: jdbc:h2:mem:project
    username: root
  h2:
    console:
      enabled: true
  jpa:
    .database-platform: org.hibernate.dialect.H2Dialect
