spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:database
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    .database-platform: org.hibernate.dialect.H2Dialect
